trigger:
  branches:
    include:
      - master
      - master-linux

pr:
  branches:
    include:
      - master
      - master-linux

parameters:
  - name: ARTIFACTS_URL
    displayName: ARTIFACTS_URL
    type: string

jobs:
  - job: RunWindowsTests
    pool:
      vmImage: "windows-latest"
    steps:
      - script: |
          echo "Downloading extension from ${{ parameters.ARTIFACTS_URL }}"
          curl -o extension.zip ${{ parameters.ARTIFACTS_URL }}
          echo "Unzipping extension.zip"
          tar -xf extension.zip
          ls
        displayName: "Download Extension"

      - task: NodeTool@0
        inputs:
          versionSpec: "20.18.3"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Create Test Cases"
          npm run test:create
        displayName: "Run Create Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true
      - script: |
          echo "Running Emit Test Cases"
          npm run test:emit
        displayName: "Run Emit Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true
      - script: |
          echo "Running Import Test Cases"
          npm run test:import
        displayName: "Run Import Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true
      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images/**/*.png"
        displayName: "Publish screenshots to Artifacts"
