trigger:
  branches:
    include:
      - master
      - master-linux

pr:
  branches:
    include:
      - master
      - master-linux

jobs:
  - job: RunWindowsTests_3_ImportTypespecProject
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.18.3"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Import Test Cases"
          npm run test:import
        displayName: "Run Import Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images/**/*.png"
        displayName: "Publish screenshots to Artifacts"
