parameters:
  - name: jobName
    type: string
  - name: testScript
    type: string

jobs:
  - job: ${{ parameters.jobName }}
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.18.3"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running ${{ parameters.jobName }} tests"
          npm run ${{ parameters.testScript }}
        displayName: "Run ${{ parameters.jobName }} tests"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images/**/*.png"
        displayName: "Publish screenshots to Artifacts"
